drop table oauth2_role if exists;
drop table oauth2_user if exists;
drop table user_role if exists;

create table oauth2_role (id integer generated by default as identity, role varchar(255), primary key (id));
create table oauth2_user (id integer generated by default as identity, password varchar(255), username varchar(255), primary key (id));
create table user_role (user_id integer not null, role_id integer not null);

alter table user_role add constraint FK7v2sj8g5eg73ispwux8238hl9 foreign key (role_id) references oauth2_role;
alter table user_role add constraint FKrpcxsmpojfanrvg1jadatujba foreign key (user_id) references oauth2_user;